### ISSUE TITLE
It's worth noting that the setUserPrefs method doesn't return anything, which might be a problem if you want to know when the user preferences have been set.

### ISSUE THREAD

**Issue by samuelkchris** [HelpAPaw/Flutter#12]
It's worth noting that the setUserPrefs method doesn't return anything, which might be a problem if you want to know when the user preferences have been set.
# suggestions

### isUserLoggedIn:

Consider renaming this method to something like checkUserLoggedInStatus, as it better describes what the method does.
Consider changing the return type from Future<bool> to just Future, since the method doesn't actually return a boolean value - it returns a Future that resolves to a boolean value.
Consider adding some error handling code in case an error occurs while getting the SharedPreferences instance.
i.e

`
Future checkUserLoggedInStatus() async {
  try {
    final prefs = await SharedPreferences.getInstance();
    bool isLoggedIn = prefs.getBool(global.loggedIn) ?? false;
    return isLoggedIn;
  } catch (e) {
    print('Error getting user logged in status: $e');
    return false;
  }
}
`
### setUserPrefs:

Consider adding a parameter to this method that allows the caller to specify whether the user is logged in or not, rather than always setting the loggedIn key to true.
Consider adding some error handling code in case an error occurs while getting the SharedPreferences instance.
i.e

`
void setUserPrefs({bool isLoggedIn = true}) async {
  try {
    final prefs = await SharedPreferences.getInstance();
    prefs.setBool(global.loggedIn, isLoggedIn);
  } catch (e) {
    print('Error setting user prefs: $e');
  }
}
`

_Originally posted by @samuelkchris in https://github.com/HelpAPaw/Flutter/pull/7#discussion_r1141492768_

**Comment by StructPoltergeist** [comment]
Fixed in my fork.
