### ISSUE TITLE
[USER EXPERIENCE] Users should not be able to pop screens and get back to splash

### ISSUE THREAD

**Issue by svlobao** [HelpAPaw/Flutter#14]
<h3>Issue description:</h3>

Currently, if there's an issue with user experience: one can press the AppBar() "back" button, or the phone's native "back" button and get stuck on splash screen. 

I will research about whether there's good practices on preventing that and, if I find something interesting, I will be sharing with y'all

<h3> Hypothesis: </h3>

There should exist a way to either:

1. Prevent users from popping the homepage window; or
2. Refactor routing in a way users will not be able to pop the homepage screen;

**Comment by StructPoltergeist** [comment]
Fixed in my fork
