### ISSUE TITLE
Add a side menu similar to the one in the native Android app with few features

### ISSUE THREAD

**Issue by samuelkchris** [HelpAPaw/Flutter#5]
## Description:
I would like to add a side menu to the Android app, similar to the one found in the native Android app. The menu should be accessible by swiping from the left edge of the screen, and should contain a list of items that allow the user to easily navigate to different parts of the app.
I believe that a side menu would greatly improve the user experience and make it easier for users to navigate throughout the app.

## Tasks:
Implement a navigation drawer that slides in from the left edge of the screen
Populate the navigation drawer with a list of items representing different sections of the app
Highlight the currently selected item to indicate where the user currently is in the app
Consider including icons next to each item for easier recognition
Include a header at the top of the navigation drawer displaying the user's name and profile picture, if applicable

## Expected Outcome:
Users will be able to easily navigate throughout the app using the new side menu, which should improve the overall user experience.
Thanks for considering this feature request!

**Comment by StructPoltergeist** [comment]
Fixed in my fork.
